services:
  app:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PROJECT_NAME = ${PROJECT_NAME?Variable not set}
      - POSTGRES_SERVER = ${POSTGRES_SERVER?Variable not set}
      - POSTGRES_USER = ${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_DB = ${POSTGRES_DB?Variable not set}
      - FIRST_SUPERUSER = ${FIRST_SUPERUSER?Variable not set}
      - FIRST_SUPERUSER_PASSWORD = ${FIRST_SUPERUSER_PASSWORD?Variable not set}
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
